runtime: python39

service: model

env_variables:
  PYTHONUNBUFFERED: 1
  DATABASE_TYPE: supabase
  # Configura estas variables con tus credenciales de Supabase
  SUPABASE_URL: https://cnwmrcophalcymxxxhys.supabase.co
  SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNud21yY29waGFsY3lteHh4aHlzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1Mjc2MTY1OSwiZXhwIjoyMDY4MzM3NjU5fQ.-FNmrPyCI2C1zoa7QsbRk5xWjkddEDJLwfi4470Fzjc
  # Estas variables se mantienen para compatibilidad pero no se usan con Supabase
  DB_HOST: ""
  DB_PORT: "5432"
  DB_NAME: ""
  DB_USER: ""
  DB_PASSWORD: ""

automatic_scaling:
  min_instances: 0
  max_instances: 5
  target_cpu_utilization: 0.6

instance_class: F2

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
