version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development
      - DB_HOST=db 
      - DB_PORT=5432
      - DB_NAME=CanalMesiasDB
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - MODEL_URL=http://model:5000/predict
    depends_on:
      - model
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - VITE_API_URL=http://backend:3000

  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./model:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=db 
      - DB_PORT=5432
      - DB_NAME=CanalMesiasDB
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: CanalMesiasDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/backups/CanalMesiasDB_26_03_2025.backup:/docker-entrypoint-initdb.d/CanalMesiasDB_26_03_2025.backup
      - ./database/init-restore.sh:/docker-entrypoint-initdb.d/init-restore.sh

volumes:
  db_data:
    driver: local